config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:index, :show, :new, :create, :edit, :update] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :doses, dependent: :destroy, inverse_of: :cocktail
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
  accepts_nested_attributes_for :doses, reject_if: :all_blank, allow_destroy: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail, inverse_of: :doses
  belongs_to :ingredient

  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
  validates :ingredient, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, :through => :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
    @ingredients = Ingredient.all.order("name asc")
  end

  def create
    @cocktail = Cocktail.new(cocktail_permitted)
    if @cocktail.save
      redirect_to @cocktail
    else
      render "new"
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.update(cocktail_permitted)
      redirect_to @cocktail
    else
      render "edit"
    end
  end

  private

  def cocktail_permitted
    params.require(:cocktail).permit(:name, :photo, :photo_cache, doses_attributes: [:ingredient_id, :description, :_destroy, :cocktail_permittedid])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @ingredient = Ingredient.all
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = Ingredient.all

    @dose = Dose.new(dose_permitted)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "new"
    end
  end

  def delete
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.destroy
    redirect_to @cocktail
  end

  private

  def dose_permitted
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_dose_fields.html.erb
<div class="nested-fields">
<%= f.input :ingredient_id, collection: Ingredient.all, class: "form-control" %>
<%= f.input :description, class: "form-control" %>
<%= link_to_remove_association "remove dose", f %>
</div>

app/views/cocktails/_landing.html.erb
<% content_for :cocktails do %>
<% end %>
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.3) 50%), url('https://source.unsplash.com/random'); height: 50vh; background-position: center;">
</div>

app/views/cocktails/edit.html.erb
<div class="container">
  <%= simple_form_for @cocktail do |f| %>
  <% if @cocktail.errors.any? %>
  <div id="error-explanation">
    <ul>
      <% @cocktail.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= f.input :name, label: 'Cocktail Name', placeholder: 'Margarita' %>
  <h6>Add Doses</h6>
  <div id="doses">
    <%=  f.simple_fields_for :doses do |dose|%>
    <%= render 'dose_fields', f: dose %>
    <% end %>
    <div class="links">
     <%= link_to_add_association 'add dose', f, :doses %>
   </div>
 </div>
 <%= f.submit %>
 <% end %>
</div>

app/views/cocktails/index.html.erb
<div class="banner landing" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.3) 50%), url('https://source.unsplash.com/random'); height: 100vh; background-position: center;">
  <div class="header-title text-center">
    <h1>ONLY COCKTAILS LEFT ALIVE</h1>
  </div>
  <div class="button-landing text-center">
    <%= link_to "Browse the cocktails", "#cocktails-display", class: "btn btn-danger" %>
  </div>
</div>
<div class="container" id="cocktails-display">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-md-4">
      <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.3) 50%), url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>');">
        <div class="card-description">
          <h2><%= cocktail.name %></h2>
        </div>
        <%= link_to "", cocktail_path(cocktail), class: "card-a" %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="button-add">
    <%= link_to "Add a cocktail", new_cocktail_path(@cocktail), class: "btn btn-danger" %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container container-form">
  <div class="form-box">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <%= simple_form_for @cocktail do |f| %>
        <% if @cocktail.errors.any? %>
        <div id="error-explanation">
          <ul>
            <% @cocktail.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <%= f.input :name, label: 'Cocktail Name', placeholder: 'Margarita', class: "form-control" %>
        <div id="doses">
          <%=  f.simple_fields_for :doses do |dose|%>
          <%= render 'dose_fields', f: dose %>
          <% end %>
          <div class="links">
           <%= link_to_add_association 'add dose', f, :doses, class: "btn btn-danger btn-add"%>
         </div>
         <%= f.input :photo, class: "form-control" %>
         <%= f.input :photo_cache, as: :hidden %>
       </div>
       <%= f.submit %>
       <% end %>
     </div>
   </div>
 </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner-container">
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.3) 50%), url('<%= cl_image_path @cocktail.photo, height: 300, width: 400, crop: :fill %>'); height: 50vh; background-position: center;">
    <h1 class="text-center"><%= @cocktail.name %></h1>
  </div>
</div>
<div class="header-cocktail">
  <div class="container">

    <div class="cocktail-info">
      <div class="row">
        <% @cocktail.doses.each do |dose| %>
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
          <div class="cocktail-description">
            <h5><%= dose.ingredient.name %></h5>
            <p><%= dose.description %></p>
          </div>
        </div>
        <% end %>
        <%= link_to 'Add ingredient', edit_cocktail_path(@cocktail), class: "btn btn-danger" %>
        <br>
        <%= link_to 'Back', cocktails_path, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="navbar-wagon">
    <!-- Logo -->
    <%= link_to cocktails_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://source.unsplash.com/random/60x60" %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <!-- Links -->
      <%= link_to "Cocktails", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Ingredients", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Hangover", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://source.unsplash.com/random/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Some mobile link</a></li>
          <li><a href="#">Other one</a></li>
          <li><a href="#">Other one</a></li>
        </ul>
      </div>
    </div>
  </div>
  <%= yield %>
</body>
</html>